### ISSUE TITLE
Add statisctics integration

### ISSUE THREAD

**Issue by vchekan** [jet/FsKafka#3]
### Description

Confluent kafka publish internal statistics (instrumentation) in OnStatistics event. It is published as string in JSON format. 
It is much better if the library would do json parsing and expose strong-typed event object.

TODO: discuss with confluent developers possibility to change C driver to publish Protobuf-serialized statistics object. This would benefit all clients by avoiding the need to implement json parsing.

**Comment by bartelink** [comment]
Closing as this is never going to happen. The FsKafka0 module introduced in 1.4.3 provides an onramp to the single practical/viable/maintained/tested API: `FsKafka` (which provides basic statistics logging).
