### ISSUE TITLE
Solve blocking producer buffer problem

### ISSUE THREAD

**Issue by vchekan** [jet/FsKafka#4]
### Description

Confluent producer will block (or throw exception) when internal message buffer is full. This does not play well with async nature of F#.

Consider possible modifications to librdkafka and C# client to keep F# wrapper thin.

**Comment by bartelink** [comment]
Closing as this is never going to happen. The FsKafka0 module introduced in 1.4.3 provides an onramp to the single practical/viable/maintained/tested API: `FsKafka`.
