### ISSUE TITLE
QueryWatermarkOffsets queries one partition at the time

### ISSUE THREAD

**Issue by vchekan** [jet/FsKafka#6]
### Description

QueryWatermarkOffsets queries one partition at the time, which is slow and unreasonable because kafka protocol allows querying multiple topics and all partitions.

Expose override which query all partitions and maybe list of topics.

**Comment by bartelink** [comment]
Closing as this is never going to happen. The FsKafka0 module introduced in 1.4.3 provides an onramp to the single practical/viable/maintained/tested API: `FsKafka`.
