### ISSUE TITLE
Consumer without joining a group

### ISSUE THREAD

**Issue by vchekan** [jet/FsKafka#7]
### Description

It is possible to assign TopicPartitionOffset[] to consumer but it will join a group anyway. This cause unnecessary delay when no offset savings is required. This happen when implementing service operations, for example read last message in partition.

**Comment by bartelink** [comment]
Closing as this is never going to happen. The FsKafka0 module introduced in 1.4.3 provides an onramp to the single practical/viable/maintained/tested API: `FsKafka`.
